package com.vulab.code.domain;

// Generated Jan 17, 2016 3:21:35 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Car generated by hbm2java
 */
@Entity
@Table(name = "car", catalog = "test")
public class Car implements java.io.Serializable {

	private Integer carId;
	private String make;

	public Car() {
	}

	public Car(String make) {
		this.make = make;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "car_id", unique = true, nullable = false)
	public Integer getCarId() {
		return this.carId;
	}

	public void setCarId(Integer carId) {
		this.carId = carId;
	}

	@Column(name = "make", nullable = false, length = 45)
	public String getMake() {
		return this.make;
	}

	public void setMake(String make) {
		this.make = make;
	}

}
